FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# deps stage
  FROM base AS deps
  WORKDIR /app
  COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
  COPY web/package.json ./web/
  COPY package/drizzle/package.json ./package/drizzle/
  COPY server/package.json ./server/
  
  RUN pnpm install --frozen-lockfile
  
  # build stage
  FROM deps AS builder
  WORKDIR /app
  COPY package/drizzle ./package/drizzle
  COPY web ./web
  COPY tsconfig.json ./
  COPY server ./server
  
  RUN pnpm --filter @package/drizzle run build
  RUN pnpm --filter @app/web run build
  
  # runner stage
  FROM node:22-alpine AS runner
  ENV NODE_ENV=production
  ENV PNPM_HOME="/pnpm"
  ENV PATH="$PNPM_HOME:$PATH"
  RUN corepack enable
  
  WORKDIR /app
  COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
  COPY web/package.json ./web/
  COPY package/drizzle/package.json ./package/drizzle/
  
  RUN pnpm install --frozen-lockfile --prod
  
  COPY --from=builder /app/web/build ./web/build
  COPY --from=builder /app/web/server.js ./web/server.js
  
  # into the web directory and start the server
  WORKDIR /app/web
  EXPOSE 3000
  CMD ["node", "server.js"]